#!/usr/bin/env bash
# Scaffolds everything needed to onboard a new project onto bizshore-01's
# shared "Fargate-lite" platform: a project registry entry, a Caddy
# vhost, and the exact manual steps (sudoers line, SSH key, systemd/
# GitHub Actions) that still require a human with root — this script
# never touches the live server, it only generates files + prints
# instructions.
#
# Usage:
#   ops/new-project.sh <project-name> <static|proxy> [domain] [upstream]
#
# Examples:
#   ops/new-project.sh widgetco static widgetco.bizshore.net
#   ops/new-project.sh widgetco proxy widgetco.bizshore.net widgetco-reverse-proxy:80
#
# What this generates (both files land in THIS repo, versioned, same
# "repo is the source of truth, sync to the server after every change"
# discipline as ci-deploy-shell.sh itself):
#   - ops/projects/<project-name>.conf   (from ops/projects/_TEMPLATE.conf)
#   - ops/caddy/apps/<project-name>.caddy (from ops/caddy/apps/_TEMPLATE.caddy)
#
# What it does NOT do (prints instructions instead, all require root or
# a decision only a human should make):
#   - Add the sudoers line (`/etc/sudoers.d/ci-deploy`).
#   - Generate + wire a new CI-only SSH key pair.
#   - Register the Cloudflare Tunnel route.
#   - Add an Uptime Kuma monitor.
#   - Create the new project's own GitHub Actions deploy workflow (a
#     starting skeleton is at ops/templates/deploy-workflow.yml.template
#     — copy it into the NEW project's own repo and adapt).

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: ops/new-project.sh <project-name> <static|proxy> [domain] [upstream]

  project-name   lowercase alnum/dash/underscore, matches ^[a-z0-9][a-z0-9_-]*$
                 (this is the SAME name used by app-up/app-down/app-sync
                 and becomes /data/applications/<project-name> on the server)
  static|proxy   which _TEMPLATE.caddy variant to scaffold
  domain         optional, fills the vhost's {{DOMINIO}} placeholder
  upstream       optional (proxy mode only), fills {{UPSTREAM}}
EOF
  exit 64
}

[ "$#" -ge 2 ] || usage

PROJECT="$1"
MODE="$2"
DOMAIN="${3:-<DOMINIO_AQUI>}"
UPSTREAM="${4:-<project>-reverse-proxy:80}"

if [[ ! "${PROJECT}" =~ ^[a-z0-9][a-z0-9_-]*$ ]]; then
  echo "ERROR: project name '${PROJECT}' must match ^[a-z0-9][a-z0-9_-]*\$" >&2
  echo "(this is enforced again by ci-deploy-shell.sh at deploy time — pick" >&2
  echo "a name that will actually pass, not just today's validation)" >&2
  exit 65
fi

case "${MODE}" in
static | proxy) ;;
*)
  echo "ERROR: mode must be 'static' or 'proxy', got '${MODE}'" >&2
  exit 64
  ;;
esac

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECTS_DIR="${REPO_ROOT}/ops/projects"
CADDY_APPS_DIR="${REPO_ROOT}/ops/caddy/apps"

conf_out="${PROJECTS_DIR}/${PROJECT}.conf"
caddy_out="${CADDY_APPS_DIR}/${PROJECT}.caddy"

if [ -e "${conf_out}" ]; then
  echo "ERROR: ${conf_out} already exists — pick a different name or edit it directly." >&2
  exit 1
fi
if [ -e "${caddy_out}" ]; then
  echo "ERROR: ${caddy_out} already exists — pick a different name or edit it directly." >&2
  exit 1
fi

# --- 1. Project registry entry (ops/projects/<name>.conf) ---------------

cat >"${conf_out}" <<EOF
# Registry entry for ${PROJECT}. Generated by ops/new-project.sh —
# edit freely, this is a normal file, not regenerated automatically.
PROJECT_DIR="/data/applications/${PROJECT}"
COMPOSE_FILES=("docker-compose.yml")
COMPOSE_PROFILES=()
ENV_FILES=()
SYNC_FILES=("docker-compose.yml")
EOF

echo "Wrote ${conf_out}"
echo "  -> review COMPOSE_FILES/COMPOSE_PROFILES/ENV_FILES/SYNC_FILES against"
echo "     ops/projects/_TEMPLATE.conf's comments; the defaults above assume"
echo "     a single docker-compose.yml with no profiles/extra env files."

# --- 2. Caddy vhost (ops/caddy/apps/<name>.caddy) ------------------------

if [ "${MODE}" = "static" ]; then
  cat >"${caddy_out}" <<EOF
${DOMAIN} {
    root * /srv/static/${PROJECT}
    encode zstd gzip
    try_files {path} /index.html
    file_server

    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        Permissions-Policy "geolocation=(), microphone=(), camera=()"
        -Server
    }
}
EOF
else
  cat >"${caddy_out}" <<EOF
${DOMAIN} {
    reverse_proxy ${UPSTREAM} {
        header_up X-Forwarded-Proto {scheme}
    }

    encode zstd gzip

    header {
        X-Content-Type-Options nosniff
        X-Frame-Options SAMEORIGIN
        Referrer-Policy strict-origin-when-cross-origin
        Permissions-Policy "geolocation=(), microphone=(), camera=()"
        -Server
    }
}
EOF
fi

echo "Wrote ${caddy_out}"
echo "  -> add 'import apps/${PROJECT}.caddy' to ops/caddy/Caddyfile"
echo "  -> validate: docker run --rm -v \"\$PWD/ops/caddy:/etc/caddy\" caddy:2-alpine caddy validate --config /etc/caddy/Caddyfile"

# --- 3. Manual steps (require root / a human decision) -------------------

sudoers_line="ci-deploy ALL=(root) NOPASSWD: /usr/bin/docker compose -f /data/applications/${PROJECT}/docker-compose.yml *"

cat <<EOF

============================================================
Generated files. Remaining steps — all require a human with
root on bizshore-01, none of this is automated on purpose:
============================================================

1. Commit + push these two new files in this repo.

2. Sync the wrapper + registry to the server (same discipline as any
   ci-deploy-shell.sh change — see ops/DEPLOY.md §6):
     scp ops/ci-deploy-shell.sh bizshore-server:/tmp/
     scp ops/projects/${PROJECT}.conf bizshore-server:/tmp/
     ssh bizshore-server "sudo install -o root -g root -m 755 /tmp/ci-deploy-shell.sh /usr/local/bin/ci-deploy-shell && \\
       sudo install -o root -g root -m 644 /tmp/${PROJECT}.conf /etc/ci-deploy/projects/ && \\
       rm /tmp/ci-deploy-shell.sh /tmp/${PROJECT}.conf"

3. Add ONE new sudoers line (edit with 'sudo visudo -f /etc/sudoers.d/ci-deploy'):
     ${sudoers_line}
   Scoped to this project's exact compose path — cannot be used to run
   compose against any other project's files.

4. Create /data/applications/${PROJECT}/ on the server, owned by ci-deploy:
     ssh bizshore-server "sudo install -d -o ci-deploy -g ci-deploy /data/applications/${PROJECT}"

5. Generate a dedicated CI-only SSH key pair for this project (do NOT
   reuse autotrade's or platform's key — one key per project keeps the
   blast radius of a leaked key to that one project):
     ssh-keygen -t ed25519 -f ~/.ssh/${PROJECT}-deploy-shell -C "${PROJECT}-ci-deploy"
   Add the PUBLIC key to /home/ci-deploy/.ssh/authorized_keys on the
   server with the same restrictions as the existing entries:
     command="/usr/local/bin/ci-deploy-shell",no-agent-forwarding,no-X11-forwarding,no-pty ssh-ed25519 AAAA...

6. Register the Cloudflare Tunnel route (Zero Trust dashboard -> Networks
   -> Tunnels -> bizshore-home-server -> Published application routes):
     ${DOMAIN} -> http://caddy:443   (Origin Server Name: ${DOMAIN})

7. Add an Uptime Kuma monitor for ${DOMAIN} (host-wide monitoring already
   covers autotrade/bizshore-home the same way — see ops/platform/README.md).

8. In the NEW project's own repo, copy ops/templates/deploy-workflow.yml.template
   to .github/workflows/deploy-bizshore01.yml and adapt (image names, repo
   secrets BIZSHORE01_DEPLOY_SSH_KEY_SHELL/_HOST/_USER — a fresh secret set
   per project, pointing at THIS project's new key from step 5).

9. Smoke test the wrapper end-to-end BEFORE trusting the GitHub Actions
   workflow with it — SSH in as ci-deploy using the new key from step 5
   (not your personal key, which isn't subject to the forced command):
     ssh -i ~/.ssh/${PROJECT}-deploy-shell ci-deploy@<tailscale-ip> rsync-ok
     ssh -i ~/.ssh/${PROJECT}-deploy-shell ci-deploy@<tailscale-ip> "app-up ${PROJECT}"
============================================================
EOF
